accepted = [
    "Apache-2.0",
    "MIT",
    "ISC",
    "Zlib",
    "Unicode-3.0",
    "CDLA-Permissive-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "0BSD",
    "MPL-2.0",
    "CC0-1.0",
    "OpenSSL",
    "OpenSSL-standalone",
    "SSLeay-standalone",
]
