[package]
name = "submitter"
version = "0.1.0"
edition = "2021"
description = "Submitter client for TersecPot Blind Command-Bus"
authors = ["TersecPot Contributors"]
license = "MIT"
repository = "https://github.com/tersecpot/project"


[dependencies]
aes-gcm = "0.10.3"
clap = { version = "4.0", features = ["derive"] }
fips203 = "0.4.3"
fips204 = "0.4.6"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
shared = { path = "../shared" }
tempfile = "3.0"
